const clients = [
    {
        id:1,
        name:"картошка",
        lastName:'григорьевна'
    },
    {
        id:2,
        name:"молоко",
        lastName:'павловно'
    },
    {
        id:3,
        name:"сыр",
        lastName:'александрович'
    },
    {
        id:4,
        name:"колбаса",
        lastName:'дмитриевна'
    },
    {
        id:5,
        name:"плита",
        lastName:'говриловна'
    },
    {
        id:6,
        name:"рис",
        lastName:'львович'
    },
    {
        id:7,
        name:"куркума",
        lastName:'владимировна'
    },
    {
        id:8,
        name:"рожок",
        lastName:'генадьевич'
    },
    {
        id:9,
        name:"гречка",
        lastName:'борисовна'
    },
    {
        id:10,
        name:"кумыс",
        lastName:'павлович'
    },
    {
        id:12,
        name:"картошка",
        lastName:'петровна'
    },
    {
        id:13,
        name:"кефир",
        lastName:'евкакиевич'
    },
    {
        id:14,
        name:"макарон",
        lastName:'артемович'
    },
    {
        id:15,
        name:"морковь",
        lastName:'гороховна'
    },
]